on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint-safe7579:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint.yaml@main"

  build-safe7579:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test.yaml@main"
    with:
      match-path: "test/**/*.sol"
